apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: dev
  name: email-gateway-dev-deployment
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::408153089286:role/email-gateway-secretRole
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: dev
  name: dev-email-gateway-aws-secrets
spec:
  provider: aws
  secretObjects:
  - data:
    - key: PORT
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: MAIL_SENT_TO
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: MONGO_URI
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: REDIS_HOST
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: REDIS_PORT
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: REDIS_PASSWORD
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: NFTM
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: ADMIN_CONSOLE
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: PAYMENT_ENGINE
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: P2EWEBSITE
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: KALPTANTRA_WEBSITE
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    - key: SENDINBLUE_APIKEY
      objectName: arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy
    secretName: email-secret
    type: Opaque
  parameters:
    region: ap-south-1
    objects: |
        - objectName: "arn:aws:secretsmanager:ap-south-1:408153089286:secret:dev-email-gateway-iH7Wfy"
          objectAlias: "DevEmailSecret"
